package id.bayu.processor.generator;

import com.palantir.javapoet.*;
import id.bayu.processor.model.*;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.List;

public class RepositoryImplGenerator {

    private final Filer filer;

    public RepositoryImplGenerator(Filer filer) {
        this.filer = filer;
    }

    public void generate(RepositoryDefinition repo) throws IOException {
        EntityMetadata entity = repo.getEntity();
        ClassName entityType = ClassName.bestGuess(entity.getQualifiedName());
        ClassName dataSource = ClassName.get("javax.sql", "DataSource");
        ClassName txManager = ClassName.get("id.bayu.data.transaction", "TransactionManager");
        ClassName interfaceType = ClassName.bestGuess(repo.getQualifiedName());
        ClassName objectMapper = ClassName.get("com.fasterxml.jackson.databind", "ObjectMapper");
        ClassName pageClass = ClassName.get("id.bayu.data.page", "Page");
        ClassName pageReqClass = ClassName.get("id.bayu.data.page", "PageRequest");

        // Fields
        FieldSpec dsField = FieldSpec.builder(dataSource, "dataSource", Modifier.PRIVATE, Modifier.FINAL).build();
        FieldSpec txField = FieldSpec.builder(txManager, "txManager", Modifier.PRIVATE, Modifier.FINAL).build();
        FieldSpec omField = FieldSpec.builder(objectMapper, "objectMapper", Modifier.PRIVATE, Modifier.FINAL).build();

        MethodSpec constructor = MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(dataSource, "dataSource")
                .addParameter(txManager, "txManager")
                .addParameter(objectMapper, "objectMapper")
                .addStatement("this.dataSource = dataSource")
                .addStatement("this.txManager = txManager")
                .addStatement("this.objectMapper = objectMapper")
                .build();

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(repo.getImplSimpleName())
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(interfaceType)
                .addField(dsField).addField(txField).addField(omField)
                .addMethod(constructor);

        // getConnection helper - uses txManager for transactional support
        classBuilder.addMethod(MethodSpec.methodBuilder("getConnection")
                .addModifiers(Modifier.PRIVATE)
                .returns(ClassName.get("java.sql", "Connection"))
                .addException(ClassName.get("java.sql", "SQLException"))
                .addStatement("return txManager.getConnection()")
                .build());

        // mapRow helper
        classBuilder.addMethod(generateMapRow(entity, entityType));

        // DDL method
        classBuilder.addMethod(generateGetDDL(entity));

        // @OneToMany helper methods (map/load/save/delete children)
        for (OneToManyRelation rel : entity.getOneToManyRelations()) {
            generateChildMethods(classBuilder, rel);
        }

        // CRUD methods
        classBuilder.addMethod(generateFindById(entity, entityType, repo.getIdType()));
        classBuilder.addMethod(generateFindAll(entity, entityType));
        classBuilder.addMethod(generateFindAllPaginated(entity, entityType, pageClass, pageReqClass));
        classBuilder.addMethod(generateSave(entity, entityType, repo.getIdType()));
        classBuilder.addMethod(generateDeleteById(entity, repo.getIdType()));
        classBuilder.addMethod(generateCount(entity));
        classBuilder.addMethod(generateExistsById(entity, repo.getIdType()));

        // Custom query methods
        for (QueryMethodDefinition qm : repo.getQueryMethods()) {
            classBuilder.addMethod(generateQueryMethod(qm, entity, entityType));
        }

        JavaFile javaFile = JavaFile.builder(repo.getPackageName(), classBuilder.build())
                .addFileComment("Generated by Bayu Framework - DO NOT EDIT")
                .indent("    ")
                .build();

        javaFile.writeTo(filer);
    }

    private MethodSpec generateGetDDL(EntityMetadata entity) {
        return MethodSpec.methodBuilder("getDDL")
                .addModifiers(Modifier.PUBLIC)
                .returns(String.class)
                .addStatement("return $S", entity.generateDDL())
                .build();
    }

    private MethodSpec generateMapRow(EntityMetadata entity, ClassName entityType) {
        MethodSpec.Builder builder = MethodSpec.methodBuilder("mapRow")
                .addModifiers(Modifier.PRIVATE)
                .returns(entityType)
                .addParameter(ClassName.get("java.sql", "ResultSet"), "rs")
                .addException(ClassName.get("java.sql", "SQLException"))
                .addStatement("var entity = new $T()", entityType);

        for (ColumnMapping col : entity.getRegularColumns()) {
            String setter = setterName(col);
            if (col.isElementCollection()) {
                // Deserialize JSON string to List
                builder.beginControlFlow("try");
                builder.addStatement("String $LJson = rs.getString($S)", col.fieldName(), col.columnName());
                builder.beginControlFlow("if ($LJson != null)", col.fieldName());
                builder.addStatement("entity.$L(objectMapper.readValue($LJson, objectMapper.getTypeFactory().constructCollectionType(java.util.List.class, $L.class)))",
                        setter, col.fieldName(), col.elementCollectionItemType());
                builder.endControlFlow();
                builder.nextControlFlow("catch (Exception e)");
                builder.addComment("ignore JSON parse errors");
                builder.endControlFlow();
            } else if (col.isUuid()) {
                builder.addStatement("String $LStr = rs.getString($S)", col.fieldName(), col.columnName());
                builder.beginControlFlow("if ($LStr != null)", col.fieldName());
                builder.addStatement("entity.$L(java.util.UUID.fromString($LStr))", setter, col.fieldName());
                builder.endControlFlow();
            } else if (col.needsTypecastOnGet()) {
                builder.addStatement("entity.$L(rs.$L($S, $T.class))",
                        setter, col.jdbcGetter(), col.columnName(),
                        ClassName.bestGuess(col.qualifiedJavaType()));
            } else {
                builder.addStatement("entity.$L(rs.$L($S))",
                        setter, col.jdbcGetter(), col.columnName());
            }
        }

        builder.addStatement("return entity");
        return builder.build();
    }

    private MethodSpec generateFindById(EntityMetadata entity, ClassName entityType, String idType) {
        ColumnMapping id = entity.getIdColumn();
        String sql = "SELECT * FROM " + entity.getTableName() + " WHERE " + id.columnName() + " = ?";
        ClassName optionalType = ClassName.get("java.util", "Optional");

        MethodSpec.Builder builder = MethodSpec.methodBuilder("findById")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(ParameterizedTypeName.get(optionalType, entityType))
                .addParameter(ClassName.bestGuess(idType), "id");

        builder.beginControlFlow("try (var conn = getConnection())");
        builder.beginControlFlow("try (var stmt = conn.prepareStatement($S))", sql);
        if (id.isUuid()) {
            builder.addStatement("stmt.setString(1, id.toString())");
        } else {
            builder.addStatement("stmt.$L(1, id)", id.jdbcSetter());
        }
        builder.beginControlFlow("try (var rs = stmt.executeQuery())")
                .beginControlFlow("if (rs.next())")
                .addStatement("var entity = mapRow(rs)");

        // Hydrate @OneToMany children
        for (OneToManyRelation rel : entity.getOneToManyRelations()) {
            String suffix = capitalize(rel.fieldName());
            builder.addStatement("entity.$L(load$L(conn, entity.getId()))", rel.setterName(), suffix);
        }

        builder.addStatement("return $T.of(entity)", optionalType)
                .endControlFlow()
                .addStatement("return $T.empty()", optionalType)
                .endControlFlow()
                .endControlFlow() // stmt
                .nextControlFlow("catch ($T e)", ClassName.get("java.sql", "SQLException"))
                .addStatement("throw new $T(e)", RuntimeException.class)
                .endControlFlow();

        return builder.build();
    }

    private MethodSpec generateFindAll(EntityMetadata entity, ClassName entityType) {
        String sql = "SELECT * FROM " + entity.getTableName();
        ClassName listType = ClassName.get("java.util", "List");
        ClassName arrayListType = ClassName.get("java.util", "ArrayList");

        MethodSpec.Builder builder = MethodSpec.methodBuilder("findAll")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(ParameterizedTypeName.get(listType, entityType))
                .beginControlFlow("try (var conn = getConnection())")
                .addStatement("$T<$T> results = new $T<>()", listType, entityType, arrayListType)
                .beginControlFlow("try (var stmt = conn.prepareStatement($S); var rs = stmt.executeQuery())", sql)
                .beginControlFlow("while (rs.next())")
                .addStatement("results.add(mapRow(rs))")
                .endControlFlow()
                .endControlFlow(); // close stmt+rs

        // Hydrate @OneToMany
        if (entity.hasOneToMany()) {
            builder.beginControlFlow("for (var e : results)");
            for (OneToManyRelation rel : entity.getOneToManyRelations()) {
                String suffix = capitalize(rel.fieldName());
                builder.addStatement("e.$L(load$L(conn, e.getId()))", rel.setterName(), suffix);
            }
            builder.endControlFlow();
        }

        builder.addStatement("return results")
                .nextControlFlow("catch ($T e)", ClassName.get("java.sql", "SQLException"))
                .addStatement("throw new $T(e)", RuntimeException.class)
                .endControlFlow();

        return builder.build();
    }

    private MethodSpec generateFindAllPaginated(EntityMetadata entity, ClassName entityType,
                                                 ClassName pageClass, ClassName pageReqClass) {
        String countSql = "SELECT COUNT(*) FROM " + entity.getTableName();
        String baseSql = "SELECT * FROM " + entity.getTableName();
        ClassName listType = ClassName.get("java.util", "List");
        ClassName arrayListType = ClassName.get("java.util", "ArrayList");
        ClassName mapType = ClassName.get("java.util", "Map");

        return MethodSpec.methodBuilder("findAll")
                .addModifiers(Modifier.PUBLIC)
                .returns(ParameterizedTypeName.get(pageClass, entityType))
                .addParameter(pageReqClass, "pageReq")
                .addParameter(ParameterizedTypeName.get(mapType, ClassName.get(String.class), ClassName.get(String.class)), "filters")
                .beginControlFlow("try (var conn = getConnection())")
                // Build WHERE from filters
                .addStatement("var where = new StringBuilder()")
                .addStatement("var params = new java.util.ArrayList<Object>()")
                .beginControlFlow("if (filters != null)")
                .beginControlFlow("for (var entry : filters.entrySet())")
                .addStatement("if (!entry.getValue().isEmpty()) { where.append(where.isEmpty() ? $S : $S).append(entry.getKey()).append($S); params.add(entry.getValue()); }", " WHERE ", " AND ", " = ?")
                .endControlFlow()
                .endControlFlow()
                // Count
                .addStatement("var countStmt = conn.prepareStatement($S + where)", countSql)
                .beginControlFlow("for (int i = 0; i < params.size(); i++)")
                .addStatement("countStmt.setObject(i + 1, params.get(i))")
                .endControlFlow()
                .addStatement("var countRs = countStmt.executeQuery()")
                .addStatement("countRs.next()")
                .addStatement("long total = countRs.getLong(1)")
                .addStatement("countRs.close()")
                .addStatement("countStmt.close()")
                // Query with pagination
                .addStatement("String sql = $S + where + pageReq.orderClause($S) + pageReq.limitClause()", baseSql, entity.getIdColumn().columnName())
                .addStatement("var stmt = conn.prepareStatement(sql)")
                .beginControlFlow("for (int i = 0; i < params.size(); i++)")
                .addStatement("stmt.setObject(i + 1, params.get(i))")
                .endControlFlow()
                .addStatement("var rs = stmt.executeQuery()")
                .addStatement("$T<$T> results = new $T<>()", listType, entityType, arrayListType)
                .beginControlFlow("while (rs.next())")
                .addStatement("results.add(mapRow(rs))")
                .endControlFlow()
                .addStatement("rs.close()")
                .addStatement("stmt.close()")
                .addStatement("return $T.of(results, pageReq.page(), pageReq.size(), total)", pageClass)
                .nextControlFlow("catch ($T e)", ClassName.get("java.sql", "SQLException"))
                .addStatement("throw new $T(e)", RuntimeException.class)
                .endControlFlow()
                .build();
    }

    private MethodSpec generateSave(EntityMetadata entity, ClassName entityType, String idType) {
        ColumnMapping id = entity.getIdColumn();
        List<ColumnMapping> insertCols = entity.getRegularColumns().stream()
                .filter(c -> !c.isId() || !c.isGenerated())
                .filter(c -> !c.isCreatedAt() && !c.isUpdatedAt())
                .toList();

        List<ColumnMapping> updateCols = entity.getRegularColumns().stream()
                .filter(c -> !c.isId() && !c.isCreatedAt())
                .toList();

        // INSERT columns: if UUID generated, include id in insert
        StringBuilder insertColNames = new StringBuilder();
        StringBuilder insertPlaceholders = new StringBuilder();
        boolean uuidGenerated = id.isUuid() && id.isGenerated();

        if (uuidGenerated) {
            insertColNames.append(id.columnName());
            insertPlaceholders.append("?");
        }

        // Add audit fields to insert
        boolean hasCreatedAt = entity.getRegularColumns().stream().anyMatch(ColumnMapping::isCreatedAt);
        boolean hasUpdatedAt = entity.getRegularColumns().stream().anyMatch(ColumnMapping::isUpdatedAt);

        for (ColumnMapping col : insertCols) {
            if (insertColNames.length() > 0) { insertColNames.append(", "); insertPlaceholders.append(", "); }
            insertColNames.append(col.columnName());
            insertPlaceholders.append("?");
        }
        if (hasCreatedAt) {
            if (insertColNames.length() > 0) { insertColNames.append(", "); insertPlaceholders.append(", "); }
            insertColNames.append("created_at");
            insertPlaceholders.append("?");
        }
        if (hasUpdatedAt) {
            if (insertColNames.length() > 0) { insertColNames.append(", "); insertPlaceholders.append(", "); }
            insertColNames.append("updated_at");
            insertPlaceholders.append("?");
        }

        String insertSql = "INSERT INTO " + entity.getTableName() +
                " (" + insertColNames + ") VALUES (" + insertPlaceholders + ")";

        // UPDATE columns
        StringBuilder updateSet = new StringBuilder();
        for (ColumnMapping col : updateCols) {
            if (updateSet.length() > 0) updateSet.append(", ");
            updateSet.append(col.columnName()).append(" = ?");
        }
        String updateSql = "UPDATE " + entity.getTableName() +
                " SET " + updateSet + " WHERE " + id.columnName() + " = ?";

        String idGetter = getterName(id);
        String idSetter = setterName(id);

        MethodSpec.Builder builder = MethodSpec.methodBuilder("save")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(entityType)
                .addParameter(entityType, "entity")
                .addStatement("var now = java.time.LocalDateTime.now()");

        // Check if insert or update
        builder.beginControlFlow("if (entity.$L() == null)", idGetter);

        // INSERT path
        if (uuidGenerated) {
            builder.addStatement("entity.$L(java.util.UUID.randomUUID())", idSetter);
        }

        builder.beginControlFlow("try (var conn = getConnection())");
        builder.beginControlFlow("try (var stmt = conn.prepareStatement($S" +
                        (!uuidGenerated ? ", java.sql.Statement.RETURN_GENERATED_KEYS" : "") + "))", insertSql);

        int paramIdx = 1;
        if (uuidGenerated) {
            builder.addStatement("stmt.setString($L, entity.$L().toString())", paramIdx++, idGetter);
        }
        for (ColumnMapping col : insertCols) {
            builder.addStatement(setParamStatement(col, paramIdx++, "entity"));
        }
        if (hasCreatedAt) {
            builder.addStatement("stmt.setObject($L, now)", paramIdx++);
        }
        if (hasUpdatedAt) {
            builder.addStatement("stmt.setObject($L, now)", paramIdx++);
        }

        builder.addStatement("stmt.executeUpdate()");

        if (!uuidGenerated) {
            builder.beginControlFlow("try (var keys = stmt.getGeneratedKeys())");
            builder.beginControlFlow("if (keys.next())");
            builder.addStatement("entity.$L(keys.$L(1))", idSetter, id.jdbcGetter());
            builder.endControlFlow();
            builder.endControlFlow();
        }

        builder.endControlFlow(); // close stmt

        if (hasCreatedAt) builder.addStatement("entity.setCreatedAt(now)");
        if (hasUpdatedAt) builder.addStatement("entity.setUpdatedAt(now)");

        // Cascade save children
        for (OneToManyRelation rel : entity.getOneToManyRelations()) {
            String suffix = capitalize(rel.fieldName());
            builder.addStatement("save$L(conn, entity.getId(), entity.$L())", suffix, rel.getterName());
        }

        builder.addStatement("return entity");
        builder.nextControlFlow("catch ($T e)", ClassName.get("java.sql", "SQLException"));
        builder.addStatement("throw new $T(e)", RuntimeException.class);
        builder.endControlFlow();

        // UPDATE path
        builder.nextControlFlow("else");
        builder.beginControlFlow("try (var conn = getConnection())");

        // Cascade delete old children first (orphan removal)
        for (OneToManyRelation rel : entity.getOneToManyRelations()) {
            String suffix = capitalize(rel.fieldName());
            builder.addStatement("delete$L(conn, entity.$L())", suffix, idGetter);
        }

        builder.beginControlFlow("try (var stmt = conn.prepareStatement($S))", updateSql);

        int updateParamIdx = 1;
        for (ColumnMapping col : updateCols) {
            if (col.isUpdatedAt()) {
                builder.addStatement("stmt.setObject($L, now)", updateParamIdx++);
            } else {
                builder.addStatement(setParamStatement(col, updateParamIdx++, "entity"));
            }
        }
        if (id.isUuid()) {
            builder.addStatement("stmt.setString($L, entity.$L().toString())", updateParamIdx, idGetter);
        } else {
            builder.addStatement("stmt.$L($L, entity.$L())", id.jdbcSetter(), updateParamIdx, idGetter);
        }

        builder.addStatement("stmt.executeUpdate()");
        builder.endControlFlow(); // close stmt

        if (hasUpdatedAt) builder.addStatement("entity.setUpdatedAt(now)");

        // Cascade save new children
        for (OneToManyRelation rel : entity.getOneToManyRelations()) {
            String suffix = capitalize(rel.fieldName());
            builder.addStatement("save$L(conn, entity.getId(), entity.$L())", suffix, rel.getterName());
        }

        builder.addStatement("return entity");
        builder.nextControlFlow("catch ($T e)", ClassName.get("java.sql", "SQLException"));
        builder.addStatement("throw new $T(e)", RuntimeException.class);
        builder.endControlFlow();
        builder.endControlFlow();

        return builder.build();
    }

    private String setParamStatement(ColumnMapping col, int idx, String varName) {
        String getter = getterName(col);
        if (col.isElementCollection()) {
            return "try { stmt.setString(" + idx + ", " + varName + "." + getter +
                    "() != null ? objectMapper.writeValueAsString(" + varName + "." + getter + "()) : null); } catch (Exception ex) { stmt.setString(" + idx + ", null); }";
        } else if (col.isUuid()) {
            return "stmt.setString(" + idx + ", " + varName + "." + getter + "() != null ? " + varName + "." + getter + "().toString() : null)";
        } else {
            return "stmt." + col.jdbcSetter() + "(" + idx + ", " + varName + "." + getter + "())";
        }
    }

    private MethodSpec generateDeleteById(EntityMetadata entity, String idType) {
        ColumnMapping id = entity.getIdColumn();
        String sql = "DELETE FROM " + entity.getTableName() + " WHERE " + id.columnName() + " = ?";

        MethodSpec.Builder builder = MethodSpec.methodBuilder("deleteById")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(ClassName.bestGuess(idType), "id")
                .beginControlFlow("try (var conn = getConnection())");

        // Cascade delete children first
        for (OneToManyRelation rel : entity.getOneToManyRelations()) {
            String suffix = capitalize(rel.fieldName());
            builder.addStatement("delete$L(conn, id)", suffix);
        }

        builder.beginControlFlow("try (var stmt = conn.prepareStatement($S))", sql);

        if (id.isUuid()) {
            builder.addStatement("stmt.setString(1, id.toString())");
        } else {
            builder.addStatement("stmt.$L(1, id)", id.jdbcSetter());
        }

        builder.addStatement("stmt.executeUpdate()")
                .endControlFlow() // stmt
                .nextControlFlow("catch ($T e)", ClassName.get("java.sql", "SQLException"))
                .addStatement("throw new $T(e)", RuntimeException.class)
                .endControlFlow();

        return builder.build();
    }

    private MethodSpec generateCount(EntityMetadata entity) {
        String sql = "SELECT COUNT(*) FROM " + entity.getTableName();

        return MethodSpec.methodBuilder("count")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(long.class)
                .beginControlFlow("try (var conn = getConnection(); var stmt = conn.prepareStatement($S); var rs = stmt.executeQuery())", sql)
                .addStatement("rs.next()")
                .addStatement("return rs.getLong(1)")
                .nextControlFlow("catch ($T e)", ClassName.get("java.sql", "SQLException"))
                .addStatement("throw new $T(e)", RuntimeException.class)
                .endControlFlow()
                .build();
    }

    private MethodSpec generateExistsById(EntityMetadata entity, String idType) {
        ColumnMapping id = entity.getIdColumn();
        String sql = "SELECT COUNT(*) FROM " + entity.getTableName() + " WHERE " + id.columnName() + " = ?";

        MethodSpec.Builder builder = MethodSpec.methodBuilder("existsById")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(boolean.class)
                .addParameter(ClassName.bestGuess(idType), "id")
                .beginControlFlow("try (var conn = getConnection(); var stmt = conn.prepareStatement($S))", sql);

        if (id.isUuid()) {
            builder.addStatement("stmt.setString(1, id.toString())");
        } else {
            builder.addStatement("stmt.$L(1, id)", id.jdbcSetter());
        }

        builder.beginControlFlow("try (var rs = stmt.executeQuery())")
                .addStatement("rs.next()")
                .addStatement("return rs.getLong(1) > 0")
                .endControlFlow()
                .nextControlFlow("catch ($T e)", ClassName.get("java.sql", "SQLException"))
                .addStatement("throw new $T(e)", RuntimeException.class)
                .endControlFlow();

        return builder.build();
    }

    private MethodSpec generateQueryMethod(QueryMethodDefinition qm, EntityMetadata entity, ClassName entityType) {
        ClassName listType = ClassName.get("java.util", "List");
        ClassName arrayListType = ClassName.get("java.util", "ArrayList");
        ClassName optionalType = ClassName.get("java.util", "Optional");

        TypeName returnType;
        if (qm.isCount()) returnType = TypeName.LONG;
        else if (qm.isExists()) returnType = TypeName.BOOLEAN;
        else if (qm.returnsList()) returnType = ParameterizedTypeName.get(listType, entityType);
        else if (qm.returnsOptional()) returnType = ParameterizedTypeName.get(optionalType, entityType);
        else returnType = entityType;

        MethodSpec.Builder builder = MethodSpec.methodBuilder(qm.methodName())
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType);

        for (QueryMethodDefinition.QueryParam param : qm.params()) {
            builder.addParameter(ClassName.bestGuess(param.qualifiedParamType()), param.paramName());
        }

        if (qm.params().isEmpty()) {
            builder.beginControlFlow("try (var conn = getConnection(); var stmt = conn.prepareStatement($S); var rs = stmt.executeQuery())", qm.sql());
        } else {
            builder.beginControlFlow("try (var conn = getConnection(); var stmt = conn.prepareStatement($S))", qm.sql());
            for (int i = 0; i < qm.params().size(); i++) {
                QueryMethodDefinition.QueryParam param = qm.params().get(i);
                // Check if param is UUID type
                if ("java.util.UUID".equals(param.qualifiedParamType())) {
                    builder.addStatement("stmt.setString($L, $L.toString())", i + 1, param.paramName());
                } else {
                    ColumnMapping col = findColumnForParam(entity, param);
                    String setter = col != null ? col.jdbcSetter() : "setObject";
                    builder.addStatement("stmt.$L($L, $L)", setter, i + 1, param.paramName());
                }
            }
            builder.beginControlFlow("try (var rs = stmt.executeQuery())");
        }

        if (qm.isCount()) {
            builder.addStatement("rs.next()");
            builder.addStatement("return rs.getLong(1)");
        } else if (qm.isExists()) {
            builder.addStatement("rs.next()");
            builder.addStatement("return rs.getLong(1) > 0");
        } else if (qm.returnsList()) {
            builder.addStatement("$T<$T> results = new $T<>()", listType, entityType, arrayListType);
            builder.beginControlFlow("while (rs.next())");
            builder.addStatement("results.add(mapRow(rs))");
            builder.endControlFlow();
            builder.addStatement("return results");
        } else if (qm.returnsOptional()) {
            builder.beginControlFlow("if (rs.next())");
            builder.addStatement("return $T.of(mapRow(rs))", optionalType);
            builder.endControlFlow();
            builder.addStatement("return $T.empty()", optionalType);
        } else {
            builder.beginControlFlow("if (rs.next())");
            builder.addStatement("return mapRow(rs)");
            builder.endControlFlow();
            builder.addStatement("return null");
        }

        if (!qm.params().isEmpty()) {
            builder.endControlFlow(); // close inner try (rs)
        }
        builder.nextControlFlow("catch ($T e)", ClassName.get("java.sql", "SQLException"));
        builder.addStatement("throw new $T(e)", RuntimeException.class);
        builder.endControlFlow();

        return builder.build();
    }

    // ---- @OneToMany child methods ----

    private void generateChildMethods(TypeSpec.Builder classBuilder, OneToManyRelation rel) {
        EntityMetadata child = rel.childMeta();
        ClassName childType = ClassName.bestGuess(child.getQualifiedName());
        String suffix = capitalize(rel.fieldName()); // "Items", "Addons", "ReconData"

        // mapXxxRow(ResultSet)
        classBuilder.addMethod(generateChildMapRow(child, childType, suffix, rel));

        // loadXxx(Connection, UUID)
        classBuilder.addMethod(generateLoadChildren(child, childType, suffix, rel));

        // saveXxx(Connection, UUID, List<Child>)
        classBuilder.addMethod(generateSaveChildren(child, childType, suffix, rel));

        // deleteXxx(Connection, UUID)
        classBuilder.addMethod(generateDeleteChildren(child, childType, suffix, rel));

        // Recurse for nested relations
        for (OneToManyRelation nested : rel.nested()) {
            generateChildMethods(classBuilder, nested);
        }
    }

    private MethodSpec generateChildMapRow(EntityMetadata child, ClassName childType,
                                            String suffix, OneToManyRelation rel) {
        MethodSpec.Builder builder = MethodSpec.methodBuilder("map" + suffix + "Row")
                .addModifiers(Modifier.PRIVATE)
                .returns(childType)
                .addParameter(ClassName.get("java.sql", "ResultSet"), "rs")
                .addException(ClassName.get("java.sql", "SQLException"))
                .addStatement("var child = new $T()", childType);

        for (ColumnMapping col : child.getRegularColumns()) {
            String setter = setterName(col);
            if (col.isElementCollection()) {
                builder.beginControlFlow("try");
                builder.addStatement("String $LJson = rs.getString($S)", col.fieldName(), col.columnName());
                builder.beginControlFlow("if ($LJson != null)", col.fieldName());
                builder.addStatement("child.$L(objectMapper.readValue($LJson, objectMapper.getTypeFactory().constructCollectionType(java.util.List.class, $L.class)))",
                        setter, col.fieldName(), col.elementCollectionItemType());
                builder.endControlFlow();
                builder.nextControlFlow("catch (Exception e)");
                builder.endControlFlow();
            } else if (col.isUuid()) {
                builder.addStatement("String $LStr = rs.getString($S)", col.fieldName(), col.columnName());
                builder.beginControlFlow("if ($LStr != null)", col.fieldName());
                builder.addStatement("child.$L(java.util.UUID.fromString($LStr))", setter, col.fieldName());
                builder.endControlFlow();
            } else if (col.needsTypecastOnGet()) {
                builder.addStatement("child.$L(rs.$L($S, $T.class))",
                        setter, col.jdbcGetter(), col.columnName(),
                        ClassName.bestGuess(col.qualifiedJavaType()));
            } else {
                builder.addStatement("child.$L(rs.$L($S))",
                        setter, col.jdbcGetter(), col.columnName());
            }
        }

        builder.addStatement("return child");
        return builder.build();
    }

    private MethodSpec generateLoadChildren(EntityMetadata child, ClassName childType,
                                             String suffix, OneToManyRelation rel) {
        String sql = "SELECT * FROM " + child.getTableName() + " WHERE " + rel.fkColumnName() + " = ?";
        ClassName listType = ClassName.get("java.util", "List");
        ClassName arrayListType = ClassName.get("java.util", "ArrayList");

        MethodSpec.Builder builder = MethodSpec.methodBuilder("load" + suffix)
                .addModifiers(Modifier.PRIVATE)
                .returns(ParameterizedTypeName.get(listType, childType))
                .addParameter(ClassName.get("java.sql", "Connection"), "conn")
                .addParameter(ClassName.get("java.util", "UUID"), "parentId")
                .addException(ClassName.get("java.sql", "SQLException"));

        builder.beginControlFlow("try (var stmt = conn.prepareStatement($S))", sql)
                .addStatement("stmt.setString(1, parentId.toString())")
                .beginControlFlow("try (var rs = stmt.executeQuery())")
                .addStatement("$T<$T> results = new $T<>()", listType, childType, arrayListType)
                .beginControlFlow("while (rs.next())")
                .addStatement("var child = map$LRow(rs)", suffix);

        // Load nested children
        for (OneToManyRelation nested : rel.nested()) {
            String nestedSuffix = capitalize(nested.fieldName());
            builder.addStatement("child.$L(load$L(conn, child.getId()))",
                    nested.setterName(), nestedSuffix);
        }

        builder.addStatement("results.add(child)")
                .endControlFlow()
                .addStatement("return results")
                .endControlFlow()
                .endControlFlow();

        return builder.build();
    }

    private MethodSpec generateSaveChildren(EntityMetadata child, ClassName childType,
                                             String suffix, OneToManyRelation rel) {
        ClassName listType = ClassName.get("java.util", "List");

        // Build INSERT SQL for child
        List<ColumnMapping> insertCols = child.getRegularColumns().stream()
                .filter(c -> !c.isCreatedAt() && !c.isUpdatedAt())
                .toList();

        StringBuilder colNames = new StringBuilder();
        StringBuilder placeholders = new StringBuilder();
        for (int i = 0; i < insertCols.size(); i++) {
            if (i > 0) { colNames.append(", "); placeholders.append(", "); }
            colNames.append(insertCols.get(i).columnName());
            placeholders.append("?");
        }
        // Add audit columns
        boolean hasCreatedAt = child.getRegularColumns().stream().anyMatch(ColumnMapping::isCreatedAt);
        boolean hasUpdatedAt = child.getRegularColumns().stream().anyMatch(ColumnMapping::isUpdatedAt);
        if (hasCreatedAt) { colNames.append(", created_at"); placeholders.append(", ?"); }
        if (hasUpdatedAt) { colNames.append(", updated_at"); placeholders.append(", ?"); }

        String insertSql = "INSERT INTO " + child.getTableName() +
                " (" + colNames + ") VALUES (" + placeholders + ")";

        MethodSpec.Builder builder = MethodSpec.methodBuilder("save" + suffix)
                .addModifiers(Modifier.PRIVATE)
                .addParameter(ClassName.get("java.sql", "Connection"), "conn")
                .addParameter(ClassName.get("java.util", "UUID"), "parentId")
                .addParameter(ParameterizedTypeName.get(listType, childType), "children")
                .addException(ClassName.get("java.sql", "SQLException"));

        builder.beginControlFlow("if (children == null)")
                .addStatement("return")
                .endControlFlow();
        builder.addStatement("var now = java.time.LocalDateTime.now()");

        builder.beginControlFlow("for (var child : children)");

        // Set FK
        String fkSetter = "set" + capitalize(rel.fkFieldName());
        builder.addStatement("child.$L(parentId)", fkSetter);

        // Generate UUID if null
        if (child.hasUuidId()) {
            String idGetter = getterName(child.getIdColumn());
            String idSetter = setterName(child.getIdColumn());
            builder.beginControlFlow("if (child.$L() == null)", idGetter);
            builder.addStatement("child.$L(java.util.UUID.randomUUID())", idSetter);
            builder.endControlFlow();
        }

        builder.beginControlFlow("try (var stmt = conn.prepareStatement($S))", insertSql);

        int idx = 1;
        for (ColumnMapping col : insertCols) {
            builder.addStatement(setParamStatement(col, idx++, "child"));
        }
        if (hasCreatedAt) builder.addStatement("stmt.setObject($L, now)", idx++);
        if (hasUpdatedAt) builder.addStatement("stmt.setObject($L, now)", idx++);

        builder.addStatement("stmt.executeUpdate()");
        builder.endControlFlow(); // close stmt

        // Recursively save nested children
        for (OneToManyRelation nested : rel.nested()) {
            String nestedSuffix = capitalize(nested.fieldName());
            builder.addStatement("save$L(conn, child.getId(), child.$L())",
                    nestedSuffix, nested.getterName());
        }

        builder.endControlFlow(); // close for loop

        return builder.build();
    }

    private MethodSpec generateDeleteChildren(EntityMetadata child, ClassName childType,
                                               String suffix, OneToManyRelation rel) {
        String selectIdsSql = "SELECT id FROM " + child.getTableName() + " WHERE " + rel.fkColumnName() + " = ?";
        String deleteSql = "DELETE FROM " + child.getTableName() + " WHERE " + rel.fkColumnName() + " = ?";

        MethodSpec.Builder builder = MethodSpec.methodBuilder("delete" + suffix)
                .addModifiers(Modifier.PRIVATE)
                .addParameter(ClassName.get("java.sql", "Connection"), "conn")
                .addParameter(ClassName.get("java.util", "UUID"), "parentId")
                .addException(ClassName.get("java.sql", "SQLException"));

        // If there are nested relations, delete grandchildren first
        if (!rel.nested().isEmpty()) {
            builder.beginControlFlow("try (var stmt = conn.prepareStatement($S))", selectIdsSql)
                    .addStatement("stmt.setString(1, parentId.toString())")
                    .beginControlFlow("try (var rs = stmt.executeQuery())")
                    .beginControlFlow("while (rs.next())")
                    .addStatement("var childId = java.util.UUID.fromString(rs.getString(1))");

            for (OneToManyRelation nested : rel.nested()) {
                String nestedSuffix = capitalize(nested.fieldName());
                builder.addStatement("delete$L(conn, childId)", nestedSuffix);
            }

            builder.endControlFlow() // while
                    .endControlFlow() // rs
                    .endControlFlow(); // stmt
        }

        // Delete children
        builder.beginControlFlow("try (var stmt = conn.prepareStatement($S))", deleteSql)
                .addStatement("stmt.setString(1, parentId.toString())")
                .addStatement("stmt.executeUpdate()")
                .endControlFlow();

        return builder.build();
    }

    // ---- End @OneToMany child methods ----

    private ColumnMapping findColumnForParam(EntityMetadata entity, QueryMethodDefinition.QueryParam param) {
        for (ColumnMapping col : entity.getColumns()) {
            if (col.fieldName().equalsIgnoreCase(param.paramName())) return col;
        }
        return null;
    }

    private String getterName(ColumnMapping col) {
        String type = col.qualifiedJavaType();
        String field = col.fieldName();
        boolean isBooleanType = "boolean".equals(type) || "java.lang.Boolean".equals(type);

        if (isBooleanType) {
            // If field already starts with "is", use it directly as getter
            if (field.startsWith("is") && field.length() > 2 && Character.isUpperCase(field.charAt(2))) {
                return field; // isActive -> isActive(), isMainMenu -> isMainMenu()
            }
            return "is" + capitalize(field); // active -> isActive()
        }
        return "get" + capitalize(field);
    }

    private String setterName(ColumnMapping col) {
        String type = col.qualifiedJavaType();
        String field = col.fieldName();
        boolean isBooleanType = "boolean".equals(type) || "java.lang.Boolean".equals(type);

        if (isBooleanType && field.startsWith("is") && field.length() > 2 && Character.isUpperCase(field.charAt(2))) {
            // isMainMenu -> setMainMenu (strip "is" prefix)
            return "set" + field.substring(2);
        }
        return "set" + capitalize(field);
    }

    private String capitalize(String name) {
        if (name == null || name.isEmpty()) return name;
        return Character.toUpperCase(name.charAt(0)) + name.substring(1);
    }
}
